### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `login` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Fujnky** [atom/teletype#387] opened 2018-06-15 14:29 UTC
[Enter steps to reproduce:]

Was in a session, partner got thrown out, then this error happened.

**Atom**: 1.27.2 x64
**Electron**: 2.0.2
**OS**: "Arch Linux"
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.3

### Stack Trace

Uncaught TypeError: Cannot destructure property `login` of 'undefined' or 'null'.

```
At /home/lars/.atom/packages/teletype/lib/host-portal-binding.js:66

TypeError: Cannot destructure property `login` of 'undefined' or 'null'.
    at HostPortalBinding.siteDidLeave (/packages/teletype/lib/host-portal-binding.js:66:33)
    at Portal.siteDidLeave (/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:348:21)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:27:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:156:28)
    at StarOverlayNetwork.memberDidLeave (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:290:18)
    at StarOverlayNetwork.didLoseConnectionToPeer (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:191:10)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:27:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:156:28)
    at PeerPool.didDisconnect (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:157:18)
    at PeerConnection.disconnect (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:82:10)
    at PeerConnection.handleConnectionStateChange (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:150:12)
```

### Commands

```
     -1:57.2.0 core:save (input.hidden-input)
  2x -1:02.1.0 editor:add-selection-below (input.hidden-input)
     -1:01.6.0 core:backspace (input.hidden-input)
     -0:59.8.0 core:delete (input.hidden-input)
  2x -0:57.8.0 core:backspace (input.hidden-input)
     -0:55.5.0 intentions:highlight (input.hidden-input)
     -0:55.4.0 core:save (input.hidden-input)
     -0:47.9.0 core:backspace (input.hidden-input)
     -0:46.8.0 intentions:highlight (input.hidden-input)
     -0:46.6.0 core:save (input.hidden-input)
     -0:46.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:46.3.0 snippets:expand (input.hidden-input)
     -0:46.3.0 editor:indent (input.hidden-input)
     -0:44.9.0 core:backspace (input.hidden-input)
     -0:44.5.0 intentions:highlight (input.hidden-input)
     -0:44.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.5 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
chester-atom-syntax 0.3.2 
gpp-compiler 3.0.7 
hex 0.6.2 
intentions 1.1.5 
keyboard-sounds 0.2.0 
language-latex 1.1.1 
language-matlab-octave 0.3.0 
latex-autocomplete 1.1.1 
linter 2.2.0 
linter-chktex 1.3.1 
linter-gcc 0.7.1 
linter-pycodestyle 2.1.3 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
nyancat 0.14.0 
octocat-syntax 2.2.2 
pdf-view 0.70.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.1 
teletype 0.13.3 
```

**Comment by rsese** [comment] 2018-06-15 16:50
Thanks for the report!  Can you confirm if the error is reproducible or did it just happen one time?

Also, when you say "partner got thrown out" can you clarify what that means?  Did they lose their internet connection?

**Comment by Fujnky** [comment] 2018-06-20 11:38
No, it's not reproducible, just happened once. I don't think he lost his internet connection as we were still able to talk via VoIP. There was a notification that he left my portal but he did not initiate that.

**Comment by rsese** [comment] 2018-06-20 17:11
Ok thanks for confirming @Fujnky - we also noticed that you're using an unofficial build or distribution of Atom:

> Atom : 1.27.1
> Electron: 1.8.4

Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems.

Since the error also isn't reproducible, we'll close this out for now.

---

You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/) and if you see this issue again on an official build please file a new issue, thanks!

**Closed by rsese** 2018-06-20 17:11 UTC
Labels: more-information-needed
