### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by davitonP** [atom/teletype#418] opened 2018-10-02 21:12 UTC
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version

```
### Versions

**Teletype version**: v0.13.3
**Atom version**: 1.26.1
**Platform**: linux

**Comment by rsese** [comment] 2018-11-07 23:44
Thanks for the report! I'm going to go ahead and close as a duplicate of #372 so you can subscribe there for updates if you'd like. 

> Atom version: 1.26.1

Though I don't particularly think it's related, I'd also mention that the current release version of Atom is 1.32 so I'd suggest updating if you can!

**Closed by rsese** 2018-11-07 23:44 UTC
