### ISSUE TITLE
Syntax highlighting does not kick in on peer B until file is reopened

### ISSUE THREAD

**Issue by duci9y** [atom/teletype#229] opened 2017-11-17 04:46 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

When a new file is created on peer A (the host), syntax highlighting doesn't kick in until the file is saved. However, on peer B, syntax highlighting doesn't kick in even when the file is saved. Peer A has to close and reopen the file for syntax highlighting to kick in on peer B. 

### Steps to Reproduce

1. Start a session.
2. On the host, create a new file.
3. Write a line of code in a syntax-highlighting supported language.
4. Save the file.
5. Close and reopen the file. 

**Expected behavior:**

Syntax highlighting should have kicked in on peer B at the same time as on peer A. The name of the file should've been updated. 

**Actual behavior:**

Syntax highlighting didn't kick in until the file was reopened. The file name remained 'untitled' on peer B.

**Reproduces how often:**

100%.

### Versions

Versions match on both peer A and B.

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
macOS 10.13.1 (17B48)

**Comment by as-cii** [comment] 2017-11-17 09:26
Thanks for the report, @duci9y! I am going to close this since it's a duplicate of https://github.com/atom/teletype/issues/147. 

Please, subscribe there for updates and add a 👍 emoji reaction to the issue body to let us know that you care about this bug getting fixed. We'll be using community feedback to determine where we can deliver the most benefit with the available engineering resources (i.e., full-time Atom engineers, community maintainers, and new contributors).

**Closed by as-cii** 2017-11-17 09:26 UTC
