### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by AbdullahHadi1** [atom/teletype#325] opened 2018-02-13 05:33 UTC
### Diagnostics

```
Request: GET https://api.teletype.atom.ioREDACTED
NEW MESSAGES
/protocol-version

```
### Versions

**Teletype version**: v0.7.0
**Atom version**: 1.23.3
**Platform**: win32

**Comment by rsese** [comment] 2018-02-19 20:35
I'll go ahead and close this as a duplicate of https://github.com/atom/teletype/issues/318 for now but we can re-open if necessary.

**Closed by rsese** 2018-02-19 20:35 UTC
