### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by Ismaili1995** [atom/teletype#403] opened 2018-08-24 12:42 UTC
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version

```
### Versions

**Teletype version**: v0.13.3
**Atom version**: 1.29.0
**Platform**: linux

**Comment by rsese** [comment] 2018-08-24 18:16
Thanks for the report! I'm going to go ahead and close as a duplicate of #372 so you can subscribe there for updates if you'd like. If you can, please let us know if you're consistently seeing this error or if you saw it just once.  It would also be useful to know if you use access the internet via a proxy.

**Closed by rsese** 2018-08-24 18:16 UTC
