### ISSUE TITLE
Uncaught Error: No segment found

### ISSUE THREAD

**Issue by miggiegarcia** [atom/teletype#494] opened 2020-02-12 18:38 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.4

### Stack Trace

Uncaught Error: No segment found

```
At /Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: No segment found
    at DocumentTree.findSegmentContainingPosition (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document-tree.js:77:11)
    at Document.findSegment (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1061:51)
    at Document.getLogicalRange (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1006:78)
    at Document.updateMarkers (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:182:35)
    at BufferProxy.updateMarkers (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:89:38)
    at EditorProxy.updateSelections (/packages/teletype/node_modules/@atom/teletype-client/lib/editor-proxy.js:106:22)
    at EditorBinding.updateSelections (/packages/teletype/lib/editor-binding.js:264:24)
    at marker.onDidChange (/packages/teletype/lib/editor-binding.js:88:14)
    at Function.simpleDispatch (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1212922)
    at Emitter.emit (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1214363)
    at Marker.emitChangeEvent (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:73620)
    at Marker.update (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:72674)
    at Marker.setHeadPosition (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:68833)
    at DisplayMarker.setHeadBufferPosition (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2894617)
    at DisplayMarker.setHeadScreenPosition (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2894849)
    at changePosition (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:522352)
    at Cursor.changePosition (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:530896)
    at Cursor.setScreenPosition (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:522318)
    at moveCursors.o (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:30282)
    at Array.forEach (<anonymous>)
    at transact (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:33144)
    at TextBuffer.transact (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:492268)
    at TextEditor.transact (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (/Users/resilient-coders31/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:96241)
```

### Commands

```
 15x -2:32.8.0 core:backspace (input.hidden-input)
     -2:12.9.0 core:move-left (input.hidden-input)
     -2:10.2.0 core:backspace (input.hidden-input)
     -2:08.3.0 editor:newline (input.hidden-input)
  5x -2:06.5.0 core:backspace (input.hidden-input)
     -2:04.8.0 autocomplete-plus:confirm (input.hidden-input)
     -2:04.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:49.8.0 snippets:next-tab-stop (input.hidden-input)
     -1:49.8.0 snippets:expand (input.hidden-input)
     -1:49.8.0 editor:indent (input.hidden-input)
  2x -1:48.7.0 core:backspace (input.hidden-input)
  3x -1:33.9.0 editor:newline (input.hidden-input)
  2x -1:09.5.0 core:backspace (input.hidden-input)
     -0:28.2.0 editor:newline (input.hidden-input)
  3x -0:27.1.0 core:backspace (input.hidden-input)
 10x -0:24 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
auto-indent 0.5.0 
auto-save-on-idle 1.2.1 
autosave-onchange 1.5.1 
browser-plus 0.0.98 
open-in-browsers 0.0.30 
save-autorun 0.3.3 
teletype 0.13.4 
view-in-browser 1.0.1 
```

**Comment by Arcanemagus** [comment] 2020-02-12 19:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/teletype/issues/421. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-02-12 19:13 UTC
