### ISSUE TITLE
Feature Request: Add ability to share entire folders with others

### ISSUE THREAD

**Issue by lempamo** [atom/teletype#329] opened 2018-03-02 02:18 UTC
To be specific, I'm requesting the ability to share an entire folder and all files contained within with others. This would be useful if, for example, a team wants to work on multiple different files within the same repo.

**Comment by rsese** [comment] 2018-03-02 05:45
Thanks for the feedback! Closing as a duplicate of #211 and if you're interested, the team is working on a RFC (#231) that will allow participants to navigate among all the tabs a host has opened. If you have suggestions or comments, please do not hesitate to share them in that RFC. 🙇

**Closed by rsese** 2018-03-02 05:45 UTC

**Comment by nathansobo** [comment] 2018-03-02 18:28
It's also worth noting that we definitely *want* to do this, but it's non-trivial. Tons of functionality assumes that files are local, but to support this we'll need to fetch files via RPC. We've decided to focus on the easier to implement features first that provide more value, but I totally get that it would be better to have full access to the host's project folders.
