### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by davide-giardini** [atom/teletype#245] opened 2017-11-20 17:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property '2' of undefined

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property '2' of undefined
    at EditorProxy.cursorPositionForSiteId (/packages/teletype/node_modules/@atom/teletype-client/lib/editor-proxy.js:312:57)
    at selectionLayerIdsBySiteId.forEach (/packages/teletype/node_modules/@atom/teletype-client/lib/editor-proxy.js:260:27)
    at Map.forEach (native)
    at EditorProxy.updateActivePositions (/packages/teletype/node_modules/@atom/teletype-client/lib/editor-proxy.js:254:36)
    at EditorProxy.updateSelections (/packages/teletype/node_modules/@atom/teletype-client/lib/editor-proxy.js:143:10)
    at marker.onDidChange (/packages/teletype/lib/editor-binding.js:112:26)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:428:26)
    at Marker.module.exports.Marker.update (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:369:18)
    at Marker.module.exports.Marker.setHeadPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:144:25)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker.js:146:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker.js:154:25)
    at /usr/share/atom/resources/app/src/cursor.js:60:37
    at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app/src/cursor.js:644:13)
    at Cursor.module.exports.Cursor.setScreenPosition (/usr/share/atom/resources/app/src/cursor.js:58:25)
    at /usr/share/atom/resources/app/src/text-editor.js:1984:29
    at /usr/share/atom/resources/app/src/text-editor.js:2194:19
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1687:32)
    at TextEditor.module.exports.TextEditor.moveCursors (/usr/share/atom/resources/app/src/text-editor.js:2188:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app/src/text-editor.js:1983:25)
    at TextEditorComponent.didMouseDownOnContent (/usr/share/atom/resources/app/src/text-editor-component.js:1790:25)
```

### Commands

```
     -8:16.1.0 editor:consolidate-selections (input.hidden-input)
     -8:16.1.0 core:cancel (input.hidden-input)
     -7:36.9.0 project-find:show (input.hidden-input)
     -7:34.2.0 core:confirm (input.hidden-input)
     -7:15 core:cancel (ul.list-inline.tab-bar.inset-panel)
     -7:00.9.0 core:move-up (input.hidden-input)
     -7:00.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
 56x -7:00.0 core:move-left (input.hidden-input)
     -6:21.3.0 core:save (input.hidden-input)
  5x -0:57 core:close (input.hidden-input)
     -0:53.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:50.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-js-import 1.4.0 
seti-ui 1.4.0 
teletype 0.1.4 
```

**Comment by jasonrudolph** [comment] 2017-11-20 20:14
Hi @davide-giardini! :wave: Can you remember what you were doing at the time you saw this error? Any information you can provide to help us reproduce the issue is appreciated. 🙏

**Comment by davide-giardini** [comment] 2017-11-21 09:44
Hi @jasonrudolph, I don't remember the specific action but it was something simple like opening a file or writing some code after the connection of teletype with my teammate.
We didn't notice any evident error.

**Comment by moritz275** [comment] 2017-12-07 16:45
I have the same issue here.
We were working with 3 clients here, but i cannot say how to reproduce it either.
It happend after about an hour continous work, for a few minutes it appeared over and over. It now works fine again, we changed nothing.

**Comment by jasonrudolph** [comment] 2018-04-10 19:19
Since we haven't had any reports of this error in several months, and since we've released several  updates to Teletype in that time, I'm hopeful that this issue is no longer affecting people. 🤞  I'm going to close this issue, but if you're still encountering this problem in the latest version of Teletype (currently 0.12.1), please leave a comment to let us know.

**Closed by jasonrudolph** 2018-04-10 19:19 UTC
Labels: bug, needs reproduction
