### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by krubio92** [atom/teletype#381] opened 2018-05-24 19:57 UTC
### Diagnostics

```
Request: GET atom://teletype/portal/REDACTED/protocol-version

```
### Versions

**Teletype version**: v0.13.2
**Atom version**: 1.27.1
**Platform**: win32

**Comment by rsese** [comment] 2018-05-24 23:07
Thanks for the report! I'm going to go ahead and close as a duplicate of #372 so you can subscribe there for updates if you'd like. If you can, please let us know if you're consistently seeing this error or if you saw it just once.

**Closed by rsese** 2018-05-24 23:07 UTC
