### ISSUE TITLE
Feature Request: Sidebar Chat

### ISSUE THREAD

**Issue by arosenb2** [atom/teletype#280] opened 2017-12-13 17:09 UTC
If you're pairing, it might be more beneficial to centralize the chat to a dedicated space rather than having to try to communicate via comment blocks in the files.

**Comment by Arcanemagus** [comment] 2017-12-13 18:02
Isn't this a duplicate of #221? (With the nice suggestion of doing it in a Dock item.)

**Comment by jasonrudolph** [comment] 2017-12-13 19:03
> Isn't this a duplicate of #221? 

@Arcanemagus: Thanks. Yes, I think so.

@arosenb2: I'm closing this issue as a duplicate, but please subscribe to #221 for updates and add a 👍 emoji reaction to the issue body to let us know that you care about being able to chat with collaborators via Teletype. We'll be using community feedback to determine where we can deliver the most benefit with the available engineering resources (i.e., full-time Atom engineers, community maintainers, and new contributors).

**Closed by jasonrudolph** 2017-12-13 19:03 UTC
