### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by sm967** [atom/teletype#411] opened 2018-09-10 19:01 UTC
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version

```
### Versions

**Teletype version**: v0.13.3
**Atom version**: 1.30.0
**Platform**: darwin

**Comment by sm967** [comment] 2018-09-10 19:02
Fixed.

**Comment by rsese** [comment] 2018-09-10 21:30
Thanks for the report!

> Fixed.

Just to clarify, do you mean that you only saw this error once or that you did something to make the error go away?

In any case, I'll go ahead and close as a duplicate of #372 so you can subscribe there for updates if you'd like. If you can, please let us know if you're consistently seeing this error or if you saw it just once. It would also be useful to know if you access the internet via a proxy.

**Closed by rsese** 2018-09-10 21:30 UTC
