### ISSUE TITLE
Uncaught Error: Patch does not apply

### ISSUE THREAD

**Issue by tilda** [atom/teletype#242] opened 2017-11-19 19:13 UTC
[Enter steps to reproduce:]

1. have a file open with teletype
2. leave
3. error pops up

Not reproducible all the time, but maybe this is a genuine bug, I don't know

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: GalliumOS 2.1
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.1.4

### Stack Trace

Uncaught Error: Patch does not apply

```
At /home/sst/atom/atom-1.22.1-amd64/resources/app/node_modules/text-buffer/lib/helpers.js:68

Error: Patch does not apply
    at exports.patchFromChanges (/home/sst/atom/atom-1.22.1-amd64/resources/app/node_modules/text-buffer/lib/helpers.js:68:17)
    at transactionFromSnapshot (/home/sst/atom/atom-1.22.1-amd64/resources/app/node_modules/text-buffer/lib/default-history-provider.js:564:49)
    at /home/sst/atom/atom-1.22.1-amd64/resources/app/node_modules/text-buffer/lib/default-history-provider.js:416:26
    at Array.map (native)
    at DefaultHistoryProvider.module.exports.DefaultHistoryProvider.restoreFromSnapshot (/home/sst/atom/atom-1.22.1-amd64/resources/app/node_modules/text-buffer/lib/default-history-provider.js:413:40)
    at TextBuffer.module.exports.TextBuffer.restoreDefaultHistoryProvider (/home/sst/atom/atom-1.22.1-amd64/resources/app/node_modules/text-buffer/lib/text-buffer.js:881:22)
    at BufferBinding.dispose (/packages/teletype/lib/buffer-binding.js:14:17)
    at BufferProxy.dispose (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:45:38)
    at bufferProxiesById.forEach (/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:58:19)
    at Map.forEach (native)
    at Portal.dispose (/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:57:28)
    at GuestPortalBinding.leave (/packages/teletype/lib/guest-portal-binding.js:151:34)
    at GuestPortalBindingComponent.leavePortal (/packages/teletype/lib/guest-portal-binding-component.js:42:30)
```

### Commands

```
  2x -5:07.7.0 core:move-left (input.hidden-input)
  2x -5:07.0 core:move-down (input.hidden-input)
  7x -5:06.2.0 core:move-left (input.hidden-input)
     -5:04.2.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -5:02.7.0 core:move-up (input.hidden-input)
     -5:02.5.0 core:move-right (input.hidden-input)
     -5:01.9.0 core:move-up (input.hidden-input)
     -5:01.3.0 core:backspace (input.hidden-input)
     -5:01.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -5:00.9.0 editor:newline (input.hidden-input)
     -4:57.1.0 core:move-down (input.hidden-input)
  2x -4:56.6.0 core:move-up (input.hidden-input)
     -4:54.5.0 core:move-right (input.hidden-input)
  2x -4:53.5.0 core:backspace (input.hidden-input)
     -0:34.6.0 core:save (input.hidden-input)
     -0:27.4.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
atom-live-server 2.2.0 
atom-material-ui 2.0.6 
autoclose-html 0.23.0 
emmet 2.4.3 
file-icons 2.1.13 
html-head-snippets 0.2.0 
python-indent 1.1.4 
teletype 0.1.4 
vim-mode-plus 1.20.0 
wakatime 7.0.4 
```

**Comment by tilda** [comment] 2017-11-20 02:47
caught this error while having the host go offline, somehow

**Comment by jasonrudolph** [comment] 2017-11-20 20:01
@tilda: Thanks for reporting this issue. It looks like https://github.com/atom/atom/issues/15827 might be the root cause here. A fix for that issue will likely resolve the problem you encountered. We don't yet have a fix lined up for https://github.com/atom/atom/issues/15827, but feel free to subscribe to that issue for updates.

**Comment by Ben3eeE** [comment] 2018-01-12 13:23
@jasonrudolph Do you think we can close this now that https://github.com/atom/atom/issues/15827 has been closed via https://github.com/atom/text-buffer/pull/282?

**Comment by nathansobo** [comment] 2018-01-12 16:14
I think so. Thanks @Ben3eeE! ✨

**Closed by nathansobo** 2018-01-12 16:14 UTC

**Comment by steveoh** [comment] 2018-02-28 19:16
I just got this error today when trying to share. Started with the patch does not apply, on second attempt the error changes to 

this.historyProvider.getSnapshot is not a function

**Comment by Arcanemagus** [comment] 2018-02-28 19:22
@steveoh The fixed version of `text-buffer` was [first included](https://github.com/atom/atom/commit/75f43b0b0e47641cb0b1b94d68083b2f213e1409) in Atom v1.25.0-beta0, if you are on an older version (such as the current stable version v1.24.0), it would still be possible to hit this.

**Comment by steveoh** [comment] 2018-02-28 19:24
ahhh ok @Arcanemagus, is there a patch I can apply for now?

**Comment by Arcanemagus** [comment] 2018-02-28 19:31
The simplest thing would be to just use the beta version if you need this fixed immediately, anything else would be just inviting issues. Sub-packages like that are only written for the specific state of Atom at that time.
