### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by rasoolfarhaan** [atom/teletype#327] opened 2018-02-18 06:34 UTC
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version

```
### Versions

**Teletype version**: v0.8.0
**Atom version**: 1.24.0
**Platform**: win32

**Comment by rsese** [comment] 2018-02-19 20:33
Thanks for reporting @AbdullahHadi1 - as mentioned by Jason in https://github.com/atom/teletype/issues/320#issuecomment-364241144, the team is investigating this error but in the meantime, can you give the steps detailed in https://github.com/atom/teletype/issues/318#issuecomment-363559779 a try and let us know if that resolves the error for you?

**Comment by rsese** [comment] 2018-02-19 20:35
I'll go ahead and close this as a duplicate of #318 for now but we can re-open if necessary.

**Closed by rsese** 2018-02-19 20:35 UTC
