### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'. 

### ISSUE THREAD

**Issue by roydondsouza** [atom/teletype#233] opened 2017-11-17 09:03 UTC
Restart Atom

1. Switch on Share
2. Click on Copy Button
3. Switch off Share
4. Click on Join a portal
5. Portal ID will be autofilled from clipboard
6. Click on Join
7. You will receive message not to join your own portal
8. Start Share again 
<img width="291" alt="screen shot 2017-11-17 at 2 38 58 pm" src="https://user-images.githubusercontent.com/8610709/32939317-1e2d5fb4-cba5-11e7-9475-f17452dafb28.png">
9. Click on Join with the text box empty

<img width="480" alt="screen shot 2017-11-17 at 2 28 50 pm" src="https://user-images.githubusercontent.com/8610709/32938963-f13819a0-cba3-11e7-832b-49e2a6f4e569.png">

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.1.3

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Users/techjini/.atom/packages/teletype/lib/participants-component.js:39

TypeError: Cannot match against 'undefined' or 'null'.
    at ParticipantsComponent.renderParticipant (/packages/teletype/lib/participants-component.js:39:21)
    at ParticipantsComponent.render (/packages/teletype/lib/participants-component.js:28:37)
    at Object.initialize (/packages/teletype/node_modules/etch/lib/component-helpers.js:32:31)
    at /packages/teletype/lib/participants-component.js:9:10)
    at render (/packages/teletype/node_modules/etch/lib/render.js:17:25)
    at addChildren (/packages/teletype/node_modules/etch/lib/render.js:39:24)
    at render (/packages/teletype/node_modules/etch/lib/render.js:29:21)
    at Object.initialize (/packages/teletype/node_modules/etch/lib/component-helpers.js:40:23)
    at /packages/teletype/lib/guest-portal-binding-component.js:10:10)
    at render (/packages/teletype/node_modules/etch/lib/render.js:17:25)
    at updateChildren (/packages/teletype/node_modules/etch/lib/patch.js:123:34)
    at patch (/packages/teletype/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/teletype/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/teletype/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/teletype/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/teletype/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/packages/teletype/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
  2x -4:28.7.0 core:paste (input.hidden-input)
  2x -4:19.8.0 core:backspace (input.hidden-input)
     -4:17.5.0 core:confirm (input.hidden-input)
     -3:20 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.2 
Sublime-Style-Column-Selection 1.7.4 
teletype 0.1.3 
```

**Comment by as-cii** [comment] 2017-11-17 09:20
Hello @roydondsouza, thanks for the feedback! 🙇 

I am unable to reproduce the exception following the steps you provided. Can you reproduce this consistently? Did the issue go away after trying to re-share a portal?

This seems to have happened as a result of entering incorrect input multiple times (e.g. joining your own portal, using an empty portal ID, etc.), so I am gonna still mark it as a bug but give it lower priority.

**Comment by roydondsouza** [comment] 2017-11-17 09:31
Hi @as-cii, 
This happens after every Atom restart. 

Restart Atom, repeat my steps.

I can reproduce this consistently.

**Comment by BinaryMuse** [comment] 2018-01-30 17:23
@as-cii I received this error while sitting static (no one was typing) in a shared portal. Atom 1.25.0-dev-3f7a29b86

**Comment by Ben3eeE** [comment] 2018-01-30 18:06
Testing out the provided repro steps I see this if I share and unshare while joining a portal.

The portal I am trying to join is one I created while trying to follow the repro steps and now the connection is timing out. Giving me a lot of time to click the share and unshare button.

![teletype exception](https://user-images.githubusercontent.com/1058982/35582721-de8f3118-05ef-11e8-8006-5e3c073ee998.gif)

**Comment by neutrinog** [comment] 2018-02-19 19:52
I just received this same error.

**Comment by Strum355** [comment] 2018-02-28 15:30
Got this issue with a fresh Atom install. Friend tried to connect to me on his also fresh Atom install, i got the errors on my end.
1. Turn on share
2. Friend gets my shareID and tries to join
3. Times out on his end, errors on my end

```
TypeError: Cannot match against 'undefined' or 'null'.
    at HostPortalBinding.siteDidLeave (/home/noah/.atom/packages/teletype/lib/host-portal-binding.js:65:33)
    at Portal.siteDidLeave (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:331:21)
    at Function.module.exports.Emitter.simpleDispatch (/home/noah/.atom/packages/teletype/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/home/noah/.atom/packages/teletype/node_modules/event-kit/lib/emitter.js:141:28)
    at StarOverlayNetwork.memberDidLeave (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:268:18)
    at StarOverlayNetwork.receiveLeaveNotification (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:256:10)
    at StarOverlayNetwork.receive (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:187:12)
    at Function.module.exports.Emitter.simpleDispatch (/home/noah/.atom/packages/teletype/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/home/noah/.atom/packages/teletype/node_modules/event-kit/lib/emitter.js:141:28)
    at PeerPool.didReceiveMessage (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:161:18)
    at PeerConnection.finishReceiving (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:275:10)
    at PeerConnection.receive (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:266:14)
    at RTCDataChannel.channel.onmessage (/home/noah/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:135:47)
```

No other plugins installed.

**Comment by jasonrudolph** [comment] 2018-03-06 14:38
@neutrinog @Strum355: Thanks for sharing those details. I'm sorry you ran into this issue.

We have a handful of improvements in the pipeline and resolving this issue is one those improvements. We're hoping to address this in an upcoming release.

**Comment by jasonrudolph** [comment] 2018-04-03 21:46
We haven't been able to reliably reproduce this issue, but we made some adjustments in https://github.com/atom/teletype-client/pull/58 that we hope will help. Those improvements shipped today in Teletype 0.12.0. With that in mind, I'm going to close this issue. If you still experience this problem with Teletype 0.12.0 or later, please leave a comment to let us know, and we'll reopen the issue. :bow:

**Closed by jasonrudolph** 2018-04-03 21:46 UTC
Labels: bug, priority:low

**Comment by Ben3eeE** [comment] 2018-04-04 19:13
@jasonrudolph There are two separate issues here and one of them still reproduces so I opened this as a separate issue in https://github.com/atom/teletype/issues/357

**Comment by sguthals** [comment] 2018-04-09 16:11
👋 I received this error today:
<img width="487" alt="screen shot 2018-04-09 at 8 33 46 am" src="https://user-images.githubusercontent.com/1314285/38509101-d4766680-3bd5-11e8-83d8-c747b4bf2b1d.png">
And "View Issue" brought me here. 

I am running Teletype 0.12.0
