### ISSUE TITLE
Add a way to use fixed tokens

### ISSUE THREAD

**Issue by crubier** [atom/teletype#249] opened 2017-11-21 09:53 UTC
Add a way to use a fixed token instead of generating a new token on each "sharing" session.

Use case: So I can collaborate with my colleagues without having to always send a new token through slack.

**Comment by jasonrudolph** [comment] 2017-11-21 19:12
Duplicate of #213

---

I _think_ this need would be satisfied by #213, so I'm going to close this as a duplicate. If I'm misunderstanding the request, please let me know. :smile:

Please subscribe to #213 for updates and add a 👍 emoji reaction to the issue body to let us know that you care about having an easier way to quickly start collaborating with someone you've previously collaborated with. We'll be using community feedback to determine where we can deliver the most benefit with the available engineering resources (i.e., full-time Atom engineers, community maintainers, and new contributors).

**Closed by jasonrudolph** 2017-11-21 19:12 UTC

**Comment by crubier** [comment] 2017-11-21 21:43
Yes #213 is probably a better way to do this, I'll upvote it thank you !
