### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by Chraa** [atom/teletype#442] opened 2019-03-12 09:16 UTC
### Diagnostics

```
Request: GET atom://teletype/portal/REDACTED/protocol-version


from devtools / console:
/root/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/rest-gateway.js:33 Fetch API cannot load atom://teletype/portal/REDACTED/protocol-version. URL scheme must be "http" or "https" for CORS request.

/root/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/rest-gateway.js:33 Fetch API cannot load atom://teletype/portal/REDACTED/protocol-version. URL scheme must be "http" or "https" for CORS request.
```
### Versions

**Teletype version**: v0.13.3
**Atom version**: 1.35.0
**Platform**: linux

No Proxy used.

**Comment by rsese** [comment] 2019-03-12 22:17
Thanks for the report! I'm going to go ahead and close as a duplicate of #372 so you can subscribe there for updates if you'd like. If you can, please let us know if you're consistently seeing this error or if you saw it just once. Thanks for letting us know that you're not using a proxy :+1:

**Closed by rsese** 2019-03-12 22:17 UTC

**Comment by Chraa** [comment] 2019-03-13 14:35
This is a constant error, have tried various things (uninstall etc,, ) No fix yet..

**Comment by rsese** [comment] 2019-03-13 21:49
:+1: If it's easy to test, have you seen the same behavior when connected to a different network?

Also, what's the full output of `atom -v`?

**Comment by Chraa** [comment] 2019-03-13 22:48
We can close this, i did a total wipe of atom and teletype -> reinstalled all of it and its working ! TY

**Comment by rsese** [comment] 2019-03-14 03:55
Interesting, I wonder what the issue was 🤔  In any case, glad things are working for you now - the issue is already closed as a duplicate of https://github.com/atom/teletype/issues/372 so if you start hitting this error again, feel free to subscribe to https://github.com/atom/teletype/issues/372 if you'd like.
