### ISSUE TITLE
Fuzzy Finder opens Untitled file instead of shared one.

### ISSUE THREAD

**Issue by gold604** [atom/teletype#355] opened 2018-04-02 10:00 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

When using Fuzzy Finder via shortcut CTRL + B to open shared file, it opens Untitled file. CTRL+ALT works fine though.

### Steps to Reproduce

0. Create Teletype server and join, load multiple files to guest buffer.
1. Use shortcut CTRL+B or open 'Fuzzy Finder: Toggle Buffer Finder' via command pallete.
2. Select a shared file from buffer and enter.
3. Untitled page pops out.

**Expected behavior:**
I expected to open a demanded(shared file via teletype) file from fuzzy finder list, but Untitled file showed up.

**Reproduces how often:**

It happens every time to me.

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 3.6.3
git 2.14.2.windows.3
visual studio

OS: Windows 10 Pro version 1709

### Additional Information

[Here is a gif](https://i.imgur.com/6ZFfoaC.gif)

**Comment by rsese** [comment] 2018-04-02 19:15
Thanks for the report!  I can reproduce the behavior with Atom 1.25 on macOS 10.12.6 but it works in 1.26 which is currently in beta.  The [blog post](http://blog.atom.io/2018/03/29/new-in-teletype-faster-setup-and-improved-multi-file-support.html) about this functionality mentions that it's available starting in Atom 1.26 (and I confirmed that buffer finder works there).

The behavior is a bit confusing on 1.25 since buffer finder shows you the remote buffers (should it not in 1.25?) but I'll tentatively close this since I believe the fuzzy finder functionality is tied to 1.26 as mentioned in the blog post (please re-open if I'm wrong @jasonrudolph @as-cii :v:).

**Closed by rsese** 2018-04-02 19:15 UTC

**Comment by gold604** [comment] 2018-04-02 19:29
@rsese I have just installed the beta and it works. Thanks for the info.
