### ISSUE TITLE
[feature request] allow sharing an entire project instead of just a file.

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom/teletype#288] opened 2017-12-16 03:59 UTC
Not sure if this will cause any issue or if this sits within the scope of the package, but it would be nice if people can collaborate on a project instead of sharing files one by one. Thanks.

**Comment by rsese** [comment] 2017-12-16 05:36
Thanks for the feedback!  Closing as a duplicate of https://github.com/atom/teletype/issues/211 but feel free to add a 👍 to the issue body of https://github.com/atom/teletype/issues/211 to show your support for the enhancement.  Also see Jason's comment for an update on sharing multiple files /cc https://github.com/atom/teletype/issues/211#issuecomment-350841436 which is now possible as of Teletype 3.0:

http://blog.atom.io/2017/12/12/atom-1-23.html

**Closed by rsese** 2017-12-16 05:36 UTC
