### ISSUE TITLE
JS and CSS Linter error on guest side

### ISSUE THREAD

**Issue by gobbi9** [atom/teletype#241] opened 2017-11-18 12:55 UTC
Javascript and CSS Linters show errors in the console on the guest side when a file is edited.

- it does not matter who edits the file
- I did not test what happens for more than one guest
- the HTML, YAML and JSON linters seem to work fine

When the gest is **not** connected to teletype, the linters work just fine. Host seems to be unaffected.

### When editing a .js file:
```
[Linter] Error running JSHint Error: Failed to spawn command `/opt/atom/atom`. Make sure `/opt/atom/atom` is installed and on your PATH
    at /home/gobbi9/.atom/packages/linter-csslint/node_modules/atom-linter/lib/helpers.js:130
    at process._tickCallback (internal/process/next_tick.js:103)
```

### When editing a .css file:
```
[Linter] Error running CSSLint Error: Failed to spawn command `/home/gobbi9/.atom/packages/linter-csslint/node_modules/.bin/csslint`. Make sure `/home/gobbi9/.atom/packages/linter-csslint/node_modules/.bin/csslint` is installed and on your PATH
    at /home/gobbi9/.atom/packages/linter-csslint/node_modules/atom-linter/lib/helpers.js:130
    at process._tickCallback (internal/process/next_tick.js:103)
```

### Affected packages
```json
	{
		"name": "linter-csslint",
		"version": "2.0.0"
	},
	{
		"name": "linter-jshint",
		"version": "3.1.6"
	},
```

### Installed packages
```json
[
	{
		"name": "about",
		"version": "1.7.8"
	},
	{
		"name": "archive-view",
		"version": "0.63.3"
	},
	{
		"name": "atom-dark-syntax",
		"version": "0.28.0",
		"theme": "syntax"
	},
	{
		"name": "atom-dark-ui",
		"version": "0.53.0",
		"theme": "ui"
	},
	{
		"name": "atom-light-syntax",
		"version": "0.29.0",
		"theme": "syntax"
	},
	{
		"name": "atom-light-ui",
		"version": "0.46.0",
		"theme": "ui"
	},
	{
		"name": "atom-turtle",
		"version": "0.1.0"
	},
	{
		"name": "autoclose-html",
		"version": "0.23.0"
	},
	{
		"name": "autocomplete-atom-api",
		"version": "0.10.3"
	},
	{
		"name": "autocomplete-css",
		"version": "0.17.3"
	},
	{
		"name": "autocomplete-html",
		"version": "0.8.1"
	},
	{
		"name": "autocomplete-plus",
		"version": "2.35.11"
	},
	{
		"name": "autocomplete-python",
		"version": "1.10.3"
	},
	{
		"name": "autocomplete-snippets",
		"version": "1.11.1"
	},
	{
		"name": "autoflow",
		"version": "0.29.0"
	},
	{
		"name": "autosave",
		"version": "0.24.3"
	},
	{
		"name": "background-tips",
		"version": "0.27.1"
	},
	{
		"name": "base16-tomorrow-dark-theme",
		"version": "1.5.0",
		"theme": "syntax"
	},
	{
		"name": "base16-tomorrow-light-theme",
		"version": "1.5.0",
		"theme": "syntax"
	},
	{
		"name": "bookmarks",
		"version": "0.44.4"
	},
	{
		"name": "bracket-matcher",
		"version": "0.87.3"
	},
	{
		"name": "busy-signal",
		"version": "1.4.3"
	},
	{
		"name": "color-picker",
		"version": "2.2.5"
	},
	{
		"name": "command-palette",
		"version": "0.41.1"
	},
	{
		"name": "dalek",
		"version": "0.2.1"
	},
	{
		"name": "deprecation-cop",
		"version": "0.56.9"
	},
	{
		"name": "dev-live-reload",
		"version": "0.47.1"
	},
	{
		"name": "editorconfig",
		"version": "2.2.2"
	},
	{
		"name": "encoding-selector",
		"version": "0.23.5"
	},
	{
		"name": "exception-reporting",
		"version": "0.41.4"
	},
	{
		"name": "expose",
		"version": "0.15.0"
	},
	{
		"name": "file-icons",
		"version": "2.1.13"
	},
	{
		"name": "find-and-replace",
		"version": "0.212.2"
	},
	{
		"name": "fuzzy-finder",
		"version": "1.5.9"
	},
	{
		"name": "git-diff",
		"version": "1.3.6"
	},
	{
		"name": "git-time-machine",
		"version": "1.5.9"
	},
	{
		"name": "github",
		"version": "0.6.2"
	},
	{
		"name": "go-to-line",
		"version": "0.32.1"
	},
	{
		"name": "goto-definition",
		"version": "1.3.4"
	},
	{
		"name": "grammar-selector",
		"version": "0.49.5"
	},
	{
		"name": "highlight-selected",
		"version": "0.13.1"
	},
	{
		"name": "image-view",
		"version": "0.62.3"
	},
	{
		"name": "incompatible-packages",
		"version": "0.27.3"
	},
	{
		"name": "intentions",
		"version": "1.1.5"
	},
	{
		"name": "keybinding-resolver",
		"version": "0.38.0"
	},
	{
		"name": "language-apache",
		"version": "1.7.0"
	},
	{
		"name": "language-c",
		"version": "0.58.1"
	},
	{
		"name": "language-clojure",
		"version": "0.22.4"
	},
	{
		"name": "language-coffee-script",
		"version": "0.49.0"
	},
	{
		"name": "language-csharp",
		"version": "0.14.2"
	},
	{
		"name": "language-css",
		"version": "0.42.5"
	},
	{
		"name": "language-docker",
		"version": "1.1.8"
	},
	{
		"name": "language-ect",
		"version": "0.4.0"
	},
	{
		"name": "language-gfm",
		"version": "0.90.1"
	},
	{
		"name": "language-git",
		"version": "0.19.1"
	},
	{
		"name": "language-go",
		"version": "0.44.2"
	},
	{
		"name": "language-html",
		"version": "0.47.7"
	},
	{
		"name": "language-hyperlink",
		"version": "0.16.2"
	},
	{
		"name": "language-java",
		"version": "0.27.4"
	},
	{
		"name": "language-javascript",
		"version": "0.127.3"
	},
	{
		"name": "language-json",
		"version": "0.19.1"
	},
	{
		"name": "language-less",
		"version": "0.33.0"
	},
	{
		"name": "language-make",
		"version": "0.22.3"
	},
	{
		"name": "language-mustache",
		"version": "0.14.1"
	},
	{
		"name": "language-objective-c",
		"version": "0.15.1"
	},
	{
		"name": "language-perl",
		"version": "0.37.0"
	},
	{
		"name": "language-php",
		"version": "0.42.0"
	},
	{
		"name": "language-property-list",
		"version": "0.9.1"
	},
	{
		"name": "language-python",
		"version": "0.45.4"
	},
	{
		"name": "language-ruby",
		"version": "0.71.3"
	},
	{
		"name": "language-ruby-on-rails",
		"version": "0.25.2"
	},
	{
		"name": "language-sass",
		"version": "0.61.1"
	},
	{
		"name": "language-shellscript",
		"version": "0.25.3"
	},
	{
		"name": "language-source",
		"version": "0.9.0"
	},
	{
		"name": "language-sparql",
		"version": "0.3.0"
	},
	{
		"name": "language-sql",
		"version": "0.25.8"
	},
	{
		"name": "language-text",
		"version": "0.7.3"
	},
	{
		"name": "language-todo",
		"version": "0.29.2"
	},
	{
		"name": "language-toml",
		"version": "0.18.1"
	},
	{
		"name": "language-typescript",
		"version": "0.2.1"
	},
	{
		"name": "language-xml",
		"version": "0.35.2"
	},
	{
		"name": "language-yaml",
		"version": "0.30.2"
	},
	{
		"name": "line-ending-selector",
		"version": "0.7.3"
	},
	{
		"name": "link",
		"version": "0.31.3"
	},
	{
		"name": "linter",
		"version": "2.2.0"
	},
	{
		"name": "linter-csslint",
		"version": "2.0.0"
	},
	{
		"name": "linter-htmlhint",
		"version": "1.4.0"
	},
	{
		"name": "linter-js-yaml",
		"version": "1.2.8"
	},
	{
		"name": "linter-jshint",
		"version": "3.1.6"
	},
	{
		"name": "linter-jsonlint",
		"version": "1.3.0"
	},
	{
		"name": "linter-markdownlint",
		"version": "1.0.2"
	},
	{
		"name": "linter-ui-default",
		"version": "1.6.10"
	},
	{
		"name": "markdown-preview",
		"version": "0.159.15"
	},
	{
		"name": "markdown-preview-plus",
		"version": "2.4.16"
	},
	{
		"name": "metrics",
		"version": "1.2.6"
	},
	{
		"name": "minimap",
		"version": "4.29.7"
	},
	{
		"name": "minimap-linter",
		"version": "2.1.3"
	},
	{
		"name": "minimap-pigments",
		"version": "0.2.2"
	},
	{
		"name": "notifications",
		"version": "0.69.2"
	},
	{
		"name": "one-dark-syntax",
		"version": "1.8.0",
		"theme": "syntax"
	},
	{
		"name": "one-dark-ui",
		"version": "1.10.8",
		"theme": "ui"
	},
	{
		"name": "one-light-syntax",
		"version": "1.8.0",
		"theme": "syntax"
	},
	{
		"name": "one-light-ui",
		"version": "1.10.8",
		"theme": "ui"
	},
	{
		"name": "open-on-github",
		"version": "1.2.1"
	},
	{
		"name": "package-generator",
		"version": "1.1.1"
	},
	{
		"name": "pigments",
		"version": "0.40.2"
	},
	{
		"name": "project-manager",
		"version": "3.3.5"
	},
	{
		"name": "settings-view",
		"version": "0.251.10"
	},
	{
		"name": "snippets",
		"version": "1.1.5"
	},
	{
		"name": "solarized-dark-syntax",
		"version": "1.1.2",
		"theme": "syntax"
	},
	{
		"name": "solarized-light-syntax",
		"version": "1.1.2",
		"theme": "syntax"
	},
	{
		"name": "spell-check",
		"version": "0.72.2"
	},
	{
		"name": "status-bar",
		"version": "1.8.13"
	},
	{
		"name": "styleguide",
		"version": "0.49.7"
	},
	{
		"name": "symbols-view",
		"version": "0.118.0"
	},
	{
		"name": "sync-settings",
		"version": "0.8.3"
	},
	{
		"name": "tabs",
		"version": "0.107.2"
	},
	{
		"name": "teletype",
		"version": "0.1.2"
	},
	{
		"name": "timecop",
		"version": "0.36.0"
	},
	{
		"name": "todo-show",
		"version": "2.1.0"
	},
	{
		"name": "tree-view",
		"version": "0.217.9"
	},
	{
		"name": "tree-view-git-status",
		"version": "1.4.0"
	},
	{
		"name": "update-package-dependencies",
		"version": "0.12.0"
	},
	{
		"name": "welcome",
		"version": "0.36.5"
	},
	{
		"name": "whitespace",
		"version": "0.37.3"
	},
	{
		"name": "wrap-guide",
		"version": "0.40.2"
	}
]
```

**Comment by jasonrudolph** [comment] 2017-11-18 14:34
Thanks for the report, @gobbi9! I am going to close this since it appears to be a duplicate of https://github.com/atom/teletype/issues/228.

Please, subscribe there for updates and add a 👍 emoji reaction to the issue body to let us know that you care about linter support for remote workspaces. We'll be using community feedback to determine where we can deliver the most benefit with the available engineering resources (i.e., full-time Atom engineers, community maintainers, and new contributors).

**Closed by jasonrudolph** 2017-11-18 14:34 UTC
