### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by ibnusacad** [atom/teletype#478] opened 2019-10-02 14:41 UTC
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version

```
### Versions

**Teletype version**: v0.13.4
**Atom version**: 1.34.0
**Platform**: win64

**Comment by rsese** [comment] 2019-10-02 16:35
Thanks for the report! I'm going to go ahead and close as a duplicate of #372 so you can subscribe there for updates if you'd like. If you can, please let us know if you're consistently seeing this error or if you saw it just once. It would also be useful to know if you access the internet via a proxy.

As a side note:

> Atom version: 1.34.0

The latest stable release version of Atom is 1.40.1 so if you can, I'd suggest updating.

**Closed by rsese** 2019-10-02 16:35 UTC
