### ISSUE TITLE
Tab titles are not based on remote paths for guests

### ISSUE THREAD

**Issue by nathansobo** [atom/teletype#173] opened 2017-11-03 21:55 UTC
<img width="324" alt="screen shot 2017-11-03 at 3 39 27 pm" src="https://user-images.githubusercontent.com/1789/32397416-533af44c-c0af-11e7-89d5-edd0321dcbb3.png">

**Comment by CaptainJohnyAppleSeed** [comment] 2018-04-06 20:05
Has this been solved with [RFC-002](https://github.com/atom/teletype/pull/353), or is this still an issue?

**Comment by jasonrudolph** [comment] 2018-04-09 16:57
> Has this been solved with RFC-002, or is this still an issue?

@CaptainJohnyAppleSeed: I think the behavior that @nathansobo observed was due to a bug somewhere that prevented the tab title from reflecting any path at all. 😬 But, since we haven't seen this issue in 5 months, and since we don't have steps to reproduce it, I'm going to close this issue. If anyone runs into this issue, please let us know.

**Closed by jasonrudolph** 2018-04-09 16:57 UTC
Labels: bug
