### ISSUE TITLE
Changing the file or filename type doesn't update the shared instances

### ISSUE THREAD

**Issue by timlevett** [atom/teletype#235] opened 2017-11-17 14:42 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

If you share a new document (Untitled), start a share, have someone join, then save the document as testing.java. 

Expected: The shared user would see the file name update to testing.java, syntax highlighting would change to java.

Observed: The shared document stays Untitled and plain text syntax.

### Steps to Reproduce

1. `CTRL + N` to create new document (call this computer a)
2. Create share token
3. Have someone open the share (call them b)
4. Save the share on a's computer to `something.java`

**Expected behavior:**
File name would update and syntax would change on all computers

**Actual behavior:**

Only a's computer was updated.

**Reproduces how often:**

all the time

### Versions
```
➜  ~ atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
➜  ~ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1
➜  ~ uname -a
Darwin <removed> 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
```

**Comment by 50Wliu** [comment] 2017-11-17 14:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #147. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-11-17 14:48 UTC

**Comment by timlevett** [comment] 2017-11-17 14:51
Cool, thanks. I did search the open issues but didn't see this one. Thanks for updating it and the quick response!
