### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by eliavco** [atom/teletype#427] opened 2018-11-23 06:56 UTC
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version
Status Code: 200
Body: <html><head></head><body><script type="text/javascript">try{if(parent.document.location==document.location) window.location="https://safepage.neto.net.il/?a=block/block1&level=5&url=http%3A%2F%2Fapi.teletype.atom.io%2Fprotocol-version&cause=url_level&urllevel=0&user_id=434375&keyword=&referer=&startm=200802";}catch(e){}</script></body></html>

```
### Versions

**Teletype version**: v0.13.3
**Atom version**: 1.32.2
**Platform**: win32

**Comment by rsese** [comment] 2018-11-27 06:41
Thanks for the report! I'm going to go ahead and close as a duplicate of #372 so you can subscribe there for updates if you'd like. If you can, please let us know if you're consistently seeing this error or if you saw it just once. It would also be useful to know if you access the internet via a proxy.

**Closed by rsese** 2018-11-27 06:41 UTC

**Comment by eliavco** [comment] 2018-11-28 16:21
I see it constantly

**Comment by rsese** [comment] 2018-11-28 20:57
Thanks 👍

Do you use a proxy to access the internet?

**Comment by eliavco** [comment] 2018-11-30 10:18
I was connected to the internet when the error occurred

**Comment by rsese** [comment] 2018-11-30 18:12
Thanks so much for the extra details, I'll copy your comments over to the main issue.
