### ISSUE TITLE
Uncaught TypeError: this.resolveConnectionPromise is not a function

### ISSUE THREAD

**Issue by narjuncs** [atom/teletype#444] opened 2019-04-10 04:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.3

### Stack Trace

Uncaught TypeError: this.resolveConnectionPromise is not a function

```
At C:\Users\nagac\.atom\packages\teletype\node_modules\@atom\teletype-client\lib\star-overlay-network.js:257

TypeError: this.resolveConnectionPromise is not a function
    at StarOverlayNetwork.receiveJoinResponse (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:257:10)
    at StarOverlayNetwork.receive (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:203:12)
    at Function.simpleDispatch (/packages/teletype/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/packages/teletype/node_modules/event-kit/dist/emitter.js:257:28)
    at PeerPool.didReceiveMessage (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:161:18)
    at PeerConnection.finishReceiving (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:276:10)
    at PeerConnection.receive (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:267:14)
    at RTCDataChannel.channel.onmessage (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:135:47)
```

### Commands

```
  2x -1:31.8.0 core:paste (input.hidden-input)
     -1:23 core:select-all (input.hidden-input)
  2x -1:20.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
hyperclick 0.0.39 
language-glsl 2.0.1 
language-lua 0.9.11 
linter 1.11.18 
linter-luaparse 0.2.0 
love-ide 0.14.0 
split-diff 1.0.4 
split-diff 1.0.4 
teletype 0.13.3 
tool-bar 1.0.1 
```

**Comment by rsese** [comment] 2019-04-10 22:07
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/teletype/issues/369 so you can subscribe there for updates if you'd like.  If you have any specific steps to reproduce or any other details to share, please let us know in https://github.com/atom/teletype/issues/369.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-10 22:07 UTC

**Comment by X-Raym** [comment] 2019-11-24 23:31
@rsese Hi ! I'm having the same error message. Not sure if it is related to #369 but the result is that collab is impossible.

this is the log:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.4


### Stack Trace

Uncaught TypeError: this.resolveConnectionPromise is not a function

```
At C:\Users\Marie\.atom\packages\teletype\node_modules\@atom\teletype-client\lib\star-overlay-network.js:257

TypeError: this.resolveConnectionPromise is not a function
    at StarOverlayNetwork.receiveJoinResponse (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:257:10)
    at StarOverlayNetwork.receive (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:203:12)
    at Function.simpleDispatch (/packages/teletype/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/packages/teletype/node_modules/event-kit/dist/emitter.js:257:28)
    at PeerPool.didReceiveMessage (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:161:18)
    at PeerConnection.finishReceiving (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:276:10)
    at PeerConnection.receive (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:267:14)
    at RTCDataChannel.channel.onmessage (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:135:47)
```

### Commands

```
 20x -4:02.8.0 core:move-right (input.hidden-input)
     -3:24.3.0 core:select-all (input.hidden-input)
     -3:24 core:paste (input.hidden-input)
  2x -3:22.4.0 core:backspace (input.hidden-input)
     -2:58.7.0 core:paste (input.hidden-input)
  2x -2:57.3.0 core:backspace (input.hidden-input)
     -1:12.6.0 core:paste (input.hidden-input)
  2x -1:11.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
atom-lupa 0.7.43 
atom-python-run 0.9.7 
atom-quokka 1.0.174 
atom-runner 2.7.1 
autoupdate-packages 1.3.1 
browser-plus 0.0.98 
busy-signal 2.0.1 
click-link 1.0.11 
color-tabs 0.1.8 
compare-files 0.8.1 
docblockr 0.13.7 
file-icons 2.1.36 
fountain 0.8.1 
git-diff-details 1.4.0 
git-time-machine 2.1.0 
highlight-bad-chars 2.0.0 
highlight-nbsp 0.1.1 
highlight-selected 0.16.0 
intentions 1.1.5 
language-generic-config 1.4.0 
language-lua 0.9.11 
language-markdown 0.37.0 
language-srt 0.1.1 
linter 2.3.1 
linter-js-standard 7.0.0 
linter-ui-default 1.8.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.11.9 
minimap 4.29.9 
minimap-pigments 0.2.2 
open-in-browsers 0.0.30 
pane-browser 1.6.0 
pdf-view 0.72.0 
pigments 0.40.2 
quick-highlight 0.13.0 
script 3.25.0 
snippet-generator 0.3.2 
sort-lines 0.19.0 
source-preview 0.5.3 
space-tab 0.4.2 
split-diff 1.6.1 
standard-formatter 2.8.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
tab-control 0.6.11 
tab-smart-sort 0.3.0 
teletype 0.13.4 
terminal-tab 0.6.0 
todo-show 2.3.2 
trailing-spaces 0.4.0 
tree-view-filter 0.5.5 
vtt-helper 0.1.1 
wordcount 3.1.0 
wordpress-api 1.2.2 
```



What can I do ? 

Thanks !

**Comment by ms609** [comment] 2022-05-19 12:54
Disabling the `wordcount` package seems to have solved the issue for me.

**Comment by xxcosita3czxx** [comment] 2022-10-13 12:11
i have no package wordcount but i get this error
