### ISSUE TITLE
After restarting with the installation of Teletype, Atom throws the error: Cannot redefine property: ontrack

### ISSUE THREAD

**Issue by rubin110** [atom/teletype#382] opened 2018-05-27 22:07 UTC
*edit by @rsese to add a couple of notes*

Also reproducible on macOS 10.12.6  off of 1.29.0-dev-74c496ccd.

And as mentioned in https://github.com/atom/teletype/issues/382#issuecomment-392380722, looks like no error on 1.27.1.

---

### Description

After restarting with the installation of Teletype, Atom throws the error: Cannot redefine property: ontrack

### Steps to Reproduce

1. @annthurium wants to show you something cool and asks you to install Teletype
2. Open Atom 1.28.0-beta1 on a machine running Debian Sid under KDE 5.12.5
3. Install Teletype 1.32.2
4. Restart Atom
5. Observe

Expected:
Atom opens and @annthurium shows you a cool thing.

Actual:
Atom opens and throws the following error:

```
TypeError: Cannot redefine property: ontrack
    at Function.defineProperty (<anonymous>)
    at Object.wrapPeerConnectionEvent (/home/rubin110/.atom/packages/teletype/node_modules/webrtc-adapter/src/js/utils.js:60:10)
    at Object.shimSenderReceiverGetStats (/home/rubin110/.atom/packages/teletype/node_modules/webrtc-adapter/src/js/chrome/chrome_shim.js:288:13)
    at module.exports (/home/rubin110/.atom/packages/teletype/node_modules/webrtc-adapter/src/js/adapter_factory.js:76:18)
    at Object.<anonymous> (/home/rubin110/.atom/packages/teletype/node_modules/webrtc-adapter/src/js/adapter_core.js:13:18)
    at Object.<anonymous> (/home/rubin110/.atom/packages/teletype/node_modules/webrtc-adapter/src/js/adapter_core.js:15:3)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom-beta/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/rubin110/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:1:156)
    at Object.<anonymous> (/home/rubin110/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:280:3)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom-beta/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/rubin110/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:3:24)
    at Object.<anonymous> (/home/rubin110/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:194:3)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom-beta/resources/app.asar/static/index.js:47:45)
```

**Reproduces how often:**

100% of the time

### Versions

Atom 1.28.0-beta1
Debian Sid under KDE 5.12.5
Teletype 1.32.2

**Comment by rubin110** [comment] 2018-05-27 22:08
I should note this works fine with Atom stable, 1.27.1.

![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-f9270215-e676-42cd-b8ce-2ec822c3c497-v1.png?transparent=1&palette=1&width=246)

**Comment by maritzuhcom** [comment] 2018-05-28 19:26
Seeing same issue 
``` shell
Atom       : 1.28.0-beta1
Electron  : 2.0.1
Chrome   : 61.0.3163.100
Node        : 8.9.3
teletype   : 0.13.2
```

**Comment by rsese** [comment] 2018-05-28 20:27
Thanks for the report @rubin110 - reproduced on macOS 10.12.6 with Atom 1.29.0-dev-74c496ccd.  In my case I didn't need to restart, just installing Teletype was enough to cause the error.  The error pops up after restarting too though.  

Also had 1.27.1 installed and didn't see the error there.

**Comment by 50Wliu** [comment] 2018-05-28 21:11
Should be fixed by upgrading to at least webrtc-adapter@6.2.0, which includes https://github.com/webrtc/adapter/pull/817.  However, it looks like teletype-client should already be picking up that version?
https://github.com/atom/teletype-client/blob/f15e39c3ad451e8660781f72eb4eeee1ab4330d8/package.json#L18

**Closed** 2018-05-29 18:58 UTC
Labels: bug
