### ISSUE TITLE
Teletype double sharing not working

### ISSUE THREAD

**Issue by lovemoebius** [atom/teletype#451] opened 2019-05-14 12:37 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

### Description

I'm currently trying to set up a collaboration space with my colleague, the main issue so far is that we don't know which files the other is editing so we end up overwriting each other's code.

Our first solution was to host our projects on a shared drive, and while that works and Atom automatically updates any changes, it still doesn't allow us to work on the same file at the same time.

We tried out teletype since it seemed like the better solution. Our idea was that if we both shared our workspaces, we both would be able to see what the other was doing while also editing the same files.

Unfortunately while this seems to initially work, as soon as the second person connects and starts opening files the files opened by the first person are not synchronized anymore and will not open on the second person's Atom until the sharing is reset.

Once the first person has tried to open another file, the second person's opened files will also stop synchronizing.

### Steps to Reproduce

1. Both users add the project folder from the shared drive to Atom
2. User 1 shares his portal
3. At this point user 2 can see every file user 1 is opening and editing
4. User 2 shares his portal and user 1 connects to it
5. The files opened by user 2 open on user 1's Atom
5. Here is when the files opened by user 1 stop being opened on user 2's Atom
6. As a consequence of user 1 trying to open files, user 2's files also do not open on user 1's Atom anymore

**Expected behavior:**

Ideally I was expecting we would both see the files opened by the other and that it would just work.

**Actual behavior:**

Teletype just stops working, no files are shared between the two users.

**Reproduces how often:**

I have tried this three times and it has happened each time.

### Versions

Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

Microsoft Windows [Version 10.0.16299.1087]

I'm unsure if teletype is just not designed to be used like this, but I can't really find any information about it so I just thought I'd ask.

**Comment by rsese** [comment] 2019-05-24 02:16
Thanks for reaching out!  I don't think I've seen this described before where 2 people wanted to open portals to each other - I can see it's not disallowed and I can also see how as you described, you can get to the point where following each other starts to break down (I didn't need to use a shared drive to verify that part).

> I'm unsure if teletype is just not designed to be used like this, but I can't really find any information about it so I just thought I'd ask.

I can't speak to whether it was specifically designed to be used like this (creating portals to each other) though my guess would be "no".  So I'll tentatively close this for now since I don't believe it's a use case the team had in mind but I'll double check for you and we can always reopen if I'm wrong.

I am curious though (and I might have missed this in your description), can you clarify what the issue is if one person is the host and the other is the guest?

**Closed by rsese** 2019-05-24 02:16 UTC

**Comment by lovemoebius** [comment] 2019-05-27 11:29
> I am curious though (and I might have missed this in your description), can you clarify what the issue is if one person is the host and the other is the guest?

The main issue with that is that the guest can't access the other person's files, so we'd have to shout between each other to ask the other person to open a specific file we want to edit.

Unless there's a way to do this that I didn't find?

**Comment by rsese** [comment] 2019-05-28 21:53
Ahh ok, thanks for clarifying :+1:  There's no way to do that now but in this case I think https://github.com/atom/teletype/issues/211 is relevant.  That's a feature request asking for the ability to share a whole project rather than just whatever files the host has open and I think that would address the issue you describe.  We can't promise if/when a feature might be added, but you can subscribe there for updates if you'd like.

**Comment by creativiii** [comment] 2019-05-28 21:56
Ah well then, that explains it. 

I'll be eagerly awaiting for that feature to be added! Best of luck with development!
