### ISSUE TITLE
Unexpected token R in JSON at position 0

### ISSUE THREAD

**Issue by ThaumicTom** [atom/teletype#307] opened 2018-01-19 19:48 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

[Description of the issue]

### Steps to Reproduce

None, not sure how to recreate because it happened coincidentally

**Expected behavior:**

Starting teletype normally.

**Actual behavior:**

Error "Establishing a teletype connection failed with error: `Unexpected token R in JSON at position 0`"

**Reproduces how often:**

100% (Every Startup)

### Versions

v1.23.3 (Atom)
v.0.6.0 (Teletype)

### Additional Information

None.

**Comment by rsese** [comment] 2018-01-19 20:39
Thanks for the report!

This looks like a duplicate of https://github.com/atom/teletype/issues/266, you can subscribe there for updates if you'd like.   Just to clarify, you mentioned it reproduces "100% (Every Startup)" - do you mean that every time you start Atom or every time you open a new Atom window (or both)?

Also, if you have a moment to share the response details that Antonio asks for in https://github.com/atom/teletype/issues/266#issuecomment-350647114, that could be helpful too.

--- 
Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-19 20:39 UTC

**Comment by ThaumicTom** [comment] 2018-01-19 23:18
I meant startups with 100%. Thanks for fixing it, but it still seems to wait for an update.

**Comment by ThaumicTom** [comment] 2018-01-19 23:20
Because my browser doesn't allows me to edit posts nor supports GitHub well, I will have to write here again: With startups, I mean starting atom or restarting rhe package.
