### ISSUE TITLE
Uncaught TypeError: Patch does not apply

### ISSUE THREAD

**Issue by tomrolive** [atom/teletype#255] opened 2017-11-26 19:09 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.2.3

### Stack Trace

Uncaught TypeError: Patch does not apply

```
At C:\Users\Tom\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\default-history-provider.js:404

TypeError: Patch does not apply
    at DefaultHistoryProvider.module.exports.DefaultHistoryProvider.getSnapshot (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/default-history-provider.js:404:45)
    at TextBuffer.module.exports.TextBuffer.getHistory (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:890:45)
    at HostPortalBinding.didChangeActiveTextEditor (/packages/teletype/lib/host-portal-binding.js:82:27)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.22.1/resources/app/src/workspace.js:501:30)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.22.1/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.22.1/resources/app/src/pane-container.js:284:26)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.22.1/resources/app/src/pane.js:436:48)
    at Pane.activateItem (~/AppData/Local/atom/app-1.22.1/resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:710:25)
```

### Commands

```
     -8:05.5.0 core:confirm (input.hidden-input)
  2x -7:13.7.0 core:backspace (input.hidden-input)
     -7:08.2.0 core:confirm (input.hidden-input)
     -2:21.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
autosave-onchange 1.5.1 
browser-refresh-on-save 0.0.6 
emmet 2.4.3 
monokai-seti 0.9.0 
pigments 0.40.2 
seti-ui 1.9.0 
teletype 0.2.3 
```

**Comment by tvand7093** [comment] 2017-11-26 19:44
I'm guessing this is similar to #242.

**Comment by jasonrudolph** [comment] 2017-11-27 18:41
Thanks for the report, @tomrolive! I am going to close this since it appears to be a duplicate of #242. Please subscribe there for updates and add a 👍  emoji reaction to the issue body to let us know that you were impacted by this issue.

**Closed by jasonrudolph** 2017-11-27 18:41 UTC
