### ISSUE TITLE
Can not compile c++ code while in joined with other.

### ISSUE THREAD

**Issue by IAmTobeyMarshall** [atom/teletype#293] opened 2017-12-23 17:45 UTC
Reproduce:
Install app compiler on atom.
Join a server from friend 
After that press f5, the could should compile and run but it says cannot run without saving. Unfortunately cannot save file on local disk while in code share mode. 

![image](https://user-images.githubusercontent.com/33126358/34321526-4dc595fe-e83b-11e7-88de-8790a08f0f99.png)

**Comment by rsese** [comment] 2017-12-26 04:17
Thanks for the report!  My initial thought is this is a basically a duplicate of https://github.com/atom/teletype/issues/228 where the compiler also expects the file to be on disk but it's not in the guest's case?

**Comment by IAmTobeyMarshall** [comment] 2017-12-26 04:35
Yes, I think that's the case. Can you add the feature where remote sessions file are saved on a temp. location?

**Comment by rsese** [comment] 2017-12-29 05:10
> Can you add the feature where remote sessions file are saved on a temp. location?

I don't know how the team will address https://github.com/atom/teletype/issues/228 (though see Nathan's comment here /cc https://github.com/atom/teletype/issues/228#issuecomment-345131863) but we'll mention this scenario in https://github.com/atom/teletype/issues/228.

**Closed by rsese** 2017-12-29 05:10 UTC
