### ISSUE TITLE
how to share my folder  to others

### ISSUE THREAD

**Issue by iProgramme** [atom/teletype#232] opened 2017-11-17 09:02 UTC
I want to share my folder to other people ,but I just know how to share one file

**Comment by as-cii** [comment] 2017-11-17 09:08
Thanks for the feedback, @iProgramme! I am going to close this as a duplicate of #211.

If you are interested, we are working on a RFC (#231) that will allow participants to navigate among all the tabs a host has opened. If you have suggestions or comments, please do not hesitate to share them with us in that RFC. 🙇

**Closed by as-cii** 2017-11-17 09:08 UTC

**Comment by toewailin** [comment] 2019-01-28 05:20
> Thanks for the feedback, @iProgramme! I am going to close this as a duplicate of #211.
> 
> If you are interested, we are working on a RFC (#231) that will allow participants to navigate among all the tabs a host has opened. If you have suggestions or comments, please do not hesitate to share them with us in that RFC. 🙇

i would like to share project folder to the joiner.
