### ISSUE TITLE
[Linter + teletype] Error running PHP Error: Failed to spawn command `C:\WINDOWS\system32\cmd.exe`

### ISSUE THREAD

**Issue by newQuery** [atom/teletype#246] opened 2017-11-20 18:48 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

Hello there,
Alright, so it seems that Linter and Teletype don't really like each other.
I have reinstall Atom and only added Linter PHP and teletype in my package, and everything works fine.
Except when I join on portal, where my partner is coding in PHP, whenever he or I type something I get a Linter error.

> Error running PHP Error: Failed to spawn command `C:\WINDOWS\system32\cmd.exe`. Make sure `C:\WINDOWS\system32\cmd.exe` is installed and on your PATH
    at C:\Users\Tom\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.js:130:24

We have made some test. Since I was getting this big red boxes while he was sharing his code to me, I've invited him to participate to my workspace. At this point, I wasn't getting the red boxes anymore, but guess what ? he did! 

I'm running on a Windows 10 OS and he is on MAC OS.
If you have any questions, tests to perform, feel free to answer down below.

Night, 
Tom

**Comment by Arcanemagus** [comment] 2017-11-20 19:03
Duplicate of #228

**Comment by 50Wliu** [comment] 2017-11-20 19:31
Thank you @Arcanemagus!

**Closed by 50Wliu** 2017-11-20 19:31 UTC
